name: "Generate README"

on:
  push:
    branches: [master]
  schedule:
    - cron: "12 * * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Generate
        run: ./scripts/generate-readme

