name: 'Generate README'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '* 1 * * *'

jobs:
  fetch-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Generate
        run: |
          ./scripts/generate-readme
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit --amend --no-edit
          git push